package gui.components;



import javafx.fxml.FXML;
import javafx.geometry.Insets;
import javafx.scene.control.Label;
import javafx.scene.control.ScrollPane;
import javafx.scene.control.SplitPane;
import javafx.scene.control.Tab;
import javafx.scene.text.Text;
import transformations.ort.TransformationStatus;




/**
 * Class that controls the Tab included on the main TabPane, that has
 * the scripts information generated by the transformation.
 * @see Tab
 * @author Melina Vidoni, INGAR CONICET-UTN.
 */
public class ScriptTab extends Tab {
    private SplitPane splitPane;
    private ScrollPane scrollTypes;
    private ScrollPane scrollTables;




    /**
     * Default constructor of the component.
     */
    @FXML
    public void initialize() {
        // Prepare the split pane
        splitPane = new SplitPane();
        setContent(splitPane);

        // Start the scrolltypes pane
        newModel();
        splitPane.setDividerPositions(0.5);
        splitPane.getItems().setAll(scrollTypes, scrollTables);

        // Allow for this to be closed and add the listeners
        this.setClosable(true);
    }




    /**
     * Method that clears the scrollpanes to remove their content
     * and allow a new model to be created.
     */
    private void newModel() {
        // Start the scrolltypes pane
        scrollTypes = new ScrollPane();
        scrollTypes.setFitToWidth(true);
        scrollTypes.setFitToHeight(true);
        scrollTypes.setMinWidth(200);
        scrollTypes.setPadding(new Insets(10,10,10,10));
        SplitPane.setResizableWithParent(scrollTypes, Boolean.FALSE);

        // Start the scrolltables pane
        scrollTables = new ScrollPane();
        scrollTables.setFitToHeight(true);
        scrollTables.setFitToWidth(true);
        scrollTables.setMinWidth(200);
        scrollTables.setPadding(new Insets(10,10,10,10));
        SplitPane.setResizableWithParent(scrollTables, Boolean.FALSE);
    }





    /**
     * Method that loads the scripts inside the
     * corresponding panes.
     */
    public void showGeneratedScripts() {
        // Get the transformation status
        TransformationStatus tStatus = TransformationStatus.getInstance(false);

        // Load the types on a label
        Text typesLabel = new Text(tStatus.getTypesScript());
        typesLabel.wrappingWidthProperty().bind(scrollTypes.widthProperty());
        scrollTypes.setContent(typesLabel);

        // Load the tables on a Label
        Text tablesLabel = new Text(tStatus.getTablesScript());
        tablesLabel.wrappingWidthProperty().bind(scrollTables.widthProperty());
        scrollTables.setContent(tablesLabel);
    }
}
